# status
set-option -g status-position bottom
set -g status-interval 1
set -g escape-time 10

# start index from 1
set -g base-index 1
setw -g pane-base-index 1

# terminal colors
set -g extended-keys on
set -sag terminal-features 'xterm*:extkeys'
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",$TERM:Tc"

set -g focus-events on
set -g renumber-windows on

# change prefix
unbind C-b
unbind C-s
set-option -g prefix C-s
bind-key C-s send-prefix

# open choose-tree
bind -n M-C-k choose-tree -Z

# switch windows
bind -n M-'[' previous-window
bind -n M-']' next-window

# move windows
bind-key -n M-',' swap-window -t -1\; select-window -t -1
bind-key -n M-'.' swap-window -t +1\; select-window -t +1

# resize windows
bind-key -n C-M-'h' resize-pane -L 5
bind-key -n C-M-'l' resize-pane -R 5
bind-key -n C-M-'k' resize-pane -U 2
bind-key -n C-M-'j' resize-pane -D 2

# switch panes
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# open windows and pane
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Kill pane
bind x killp

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# reload config file
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# This is by the help of chatGPT :p
set -g status-interval 1
set -g status-right '#[bg=default]#{pane_current_path}'
set -g status-style 'bg=default'

set-option -g allow-rename off
